appinfo:
    addressEnabled: false
    copyrightYear: 2020
    demoEnabled: false
    name: RuoYi
    profile: D:/upload
    version: 4.2.0
    virtualpath: upload/
logging:
    level:
        com:
            soft:
                web:
                    dao: debug
mybatis:
    mapper-locations: classpath:com.soft.web.dao/*.xml
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            id-type: auto
    type-aliases-package: com.soft.web.entity
server:
    port: 80
    servlet:
        context-path: /
        session:
            timeout: 30m
spring:
    application:
        name: web
    datasource:
        url: jdbc:mysql://117.51.145.75:4321/fengzhu?serverTimezone=GMT%2B8
        username: root
        password: Fz$IzusLOP<^001
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
web:
    virtual-path: upload/
